name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i
      - run: |
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i
      - run: |
          npm run test

  integrity:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build action
      run: |
        npm i &&
        npm run build
    # - name: Test Action
    #   run: |
    #     npm run test:build:ci
    - name: Repository Integrity Check
      run: |
        git diff --quiet dist

  automerge:
    name: Automerge Dependabot PRs
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'dependabot[bot]'
    needs:
      - lint
      - test
      - integrity
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.0
